version: "3.8"

services:
  api_gateway:
    image: api_gateway
    container_name: api_gateway
    build:
      context: .
      dockerfile: ./api_gateway/Dockerfile
    restart: on-failure
    ports:
      - ${GATEWAY_PORT}:${GATEWAY_PORT}
    environment:
      GATEWAY_PORT: ${GATEWAY_PORT}
    networks:
      - network

  nats:
    image: nats
    container_name: nats
    restart: on-failure
    networks:
      - network

networks:
  network:
    driver: bridge

 post_db:
    image : mongo
    container_name: post_db
    environment:
    - PUID=1000
    - PGID=1000
    ports:
    - 27017:27017
    networks:
      - backend
    restart: unless-stopped

post_service:
    image: post_service
    build:
      context: ./microservices/post_service
      dockerfile: Dockerfile
    restart: on-failure
    environment:
      POST_DB_HOST: ${POST_DB_HOST}
      POST_DB_PORT: ${POST_DB_PORT}
      POST_SERVICE_PORT: ${POST_SERVICE_PORT}
    depends_on:
      - post_db
    networks:
      - network
    # expose: 
    #   - '8002'
    # ports: 
    #   - '8002:8002'